FROM node:18-alpine

#tell docker to run configure in this app directory
WORKDIR /usr/app
#copy source code into image
COPY package.json /usr/app/
COPY knexfile.js .
RUN npm install -g npm
RUN npm install bcrypt
RUN npm install -g knex

RUN npm install && npm cache clean --force
#Installs packages for React app
RUN npm install --prefix client
#Builds React app
RUN npm run --prefix client build

COPY . /usr/app/


EXPOSE 5000

CMD ["npm", "run" , "start"]
