export const ConsentTypes = {
    PHONE_CONSENT_CREATE_REQUEST:"PHONE_CONSENT_CREATE_REQUEST",
    PHONE_CONSENT_CREATE_SUCCESS:"PHONE_CONSENT_CREATE_SUCCESS",
    PHONE_CONSENT_CREATE_ERROR:"PHONE_CONSENT_CREATE_ERROR",
    PHONE_CONSENT_RESET_CREATE_LOADING:"PHONE_CONSENT_RESET_CREATE_LOADING",
    
}
