export const ProjectTypes = {
    CREATE_PROJECTS_REQUEST: "CREATE_PROJECTS_REQUEST",
    CREATE_PROJECTS_ERROR: "CREATE_PROJECTS_ERROR",
    CREATE_PROJECTS_SUCCESS: "CREATE_PROJECTS_SUCCESS",
    RESET_CREATE_PROJECT_SUCCESS:"RESET_CREATE_PROJECT_SUCCESS",

    PROJECT_UPDATE_REQUEST:"PROJECT_UPDATE_REQUEST",
    PROJECT_UPDATE_ERROR:"PROJECT_UPDATE_ERROR",
    PROJECT_UPDATE_SUCCESS:"PROJECT_UPDATE_SUCCESS",
    RESET_STATE_PROJECT_UPDATE_SUCCESS: "RESET_STATE_PROJECT_UPDATE_SUCCESS",
    RESET_STATE_PROJECT_UPDATE_ERROR: "RESET_STATE_PROJECT_UPDATE_ERROR",

    PROJECT_DELETE_REQUEST: "PROJECT_DELETE_REQUEST",
    PROJECT_DELETE_ERROR: "PROJECT_DELETE_ERROR",
    PROJECT_DELETE_SUCCESS: "PROJECT_DELETE_SUCCESS",
    RESET_STATE_PROJECT_DELETE_SUCCESS: "RESET_STATE_PROJECT_DELETE_SUCCESS",
    RESET_STATE_PROJECT_DELETE_ERROR: "RESET_STATE_PROJECT_DELETE_ERROR",

    PROJECT_LISTS_REQUEST: "PROJECT_LISTS_REQUEST",
    PROJECT_LISTS_ERROR: "PROJECT_LISTS_ERROR",
    PROJECT_LISTS_SUCCESS: "PROJECT_LISTS_SUCCESS",
    //not use yet
    PROJECT_LIST_DELETE_REQUEST:"PROJECT_LIST_DELETE_REQUEST",
    PROJECT_LIST_DELETE_SUCCESS: "PROJECT_LIST_DELETE_SUCCESS",
    PROJECT_LIST_DELETE_ERROR:"PROJECT_LIST_DELETE_ERROR"


}
