export const ProjectTypes = {
    CREATE_PROJECTS_REQUEST: "CREATE_PROJECTS_REQUEST",
    CREATE_PROJECTS_ERROR: "CREATE_PROJECTS_ERROR",
    CREATE_PROJECTS_SUCCESS: "CREATE_PROJECTS_SUCCESS",
    RESET_CREATE_PROJECT_SUCCESS:"RESET_CREATE_PROJECT_SUCCESS",


    PROJECT_LISTS_REQUEST: "PROJECT_LISTS_REQUEST",
    PROJECT_LISTS_ERROR: "PROJECT_LISTS_ERROR",
    PROJECT_LISTS_SUCCESS: "PROJECT_LISTS_SUCCESS"
}
