export const StripeType = {
    UNSUBSCRIBE_REQUEST:"UNSUBSCRIBE_REQUEST",
    UNSUBSCRIBE_SUCCESS:"UNSUBSCRIBE_SUCCESS",
    UNSUBSCRIBE_ERROR:"UNSUBSCRIBE_ERROR",
    RESET_UNSUBSCRIBE_SUCCESS:"RESET_UNSUBSCRIBE_SUCCESS"
}
