export const TaskTypes = {
    CREATE_TASKS_REQUEST:"CREATE_TASKS_REQUEST",
    CREATE_TASKS_ERROR:"CREATE_TASKS_ERROR",
    CREATE_TASKS_SUCCESS:"CREATE_TASKS_SUCCESS",

    GET_TASKS_REQUEST: "GET_TASKS_REQUEST",
    GET_TASKS_ERROR: "GET_TASKS_ERROR",
    GET_TASKS_SUCCESS: "GET_TASKS_SUCCESS",
    
    CREATE_TASK_REQUEST: "CREATE_TASK_REQUEST",
    CREATE_TASK_ERROR: "CREATE_TASK_ERROR",
    CREATE_TASK_SUCCESS: "CREATE_TASK_SUCCESS",

    
}
