export const TaskTypes = {
    CREATE_TASKS_REQUEST:"CREATE_TASKS_REQUEST",
    CREATE_TASKS_ERROR:"CREATE_TASKS_ERROR",
    CREATE_TASKS_SUCCESS:"CREATE_TASKS_SUCCESS",


    GET_TASKS_REQUEST: "GET_TASKS_REQUEST",
    GET_TASKS_ERROR: "GET_TASKS_ERROR",
    GET_TASKS_SUCCESS: "GET_TASKS_SUCCESS",

    GET_TASK_LIST_REQUEST: "GET_TASK_LIST_REQUEST",
    GET_TASK_LIST_ERROR: "GET_TASK_LIST_ERROR",
    GET_TASK_LIST_SUCCESS: "GET_TASK_LIST_SUCCESS",
    
    CREATE_TASK_REQUEST: "CREATE_TASK_REQUEST",
    CREATE_TASK_ERROR: "CREATE_TASK_ERROR",
    CREATE_TASK_SUCCESS: "CREATE_TASK_SUCCESS",
    RESET_TASK_SUCCESS: "RESET_TASK_SUCCESS",

    TASKS_LIST_DELETE_REQUEST: "TASKS_LIST_DELETE_REQUEST",
    TASKS_LIST_DELETE_SUCCESS: "TASKS_LIST_DELETE_SUCCESS",
    TASKS_LIST_DELETE_ERROR: "TASKS_LIST_DELETE_ERROR",
    TASK_LIST_RESET_SUCCESS:"TASK_LIST_RESET_SUCCESS"

    
}
