export const UserTypes = {
    SIGN_UP_USER_REQUEST: "SIGN_UP_USER_REQUEST",
    SIGN_UP_USER_ERROR: "SIGN_UP_USER_ERROR",
    SIGN_UP_USER_SUCCESS: "SIGN_UP_USER_SUCCESS",
    RESET_SIGN_UP_USER_SUCCESS: "RESET_SIGN_UP_USER_SUCCESS",
    RESET_SIGN_UP_USER_ERROR: "RESET_SIGN_UP_USER_ERROR",

    LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
    LOGIN_USER_ERROR: "LOGIN_USER_ERROR",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    RESET_LOGIN_USER_ERROR:"RESET_LOGIN_USER_ERROR",

    GOOGLE_LOGIN_USER_REQUEST: "GOOGLE_LOGIN_USER_REQUEST",
    GOOGLE_LOGIN_USER_ERROR: "GOOGLE_LOGIN_USER_ERROR",
    GOOGLE_LOGIN_USER_SUCCESS: "GOOGLE_LOGIN_USER_SUCCESS",
    GOOGLE_RESET_LOGIN_USER_ERROR: "GOOGLE_RESET_LOGIN_USER_ERROR",
    RESET_GOOGLE_SIGN_UP_USER_SUCCESS: "RESET_GOOGLE_SIGN_UP_USER_SUCCESS",
}
